apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.name" . }}-backend
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-backend
spec:
  selector:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: server-backend
  type: {{ .Values.backend.service.type }}
  ports: 
    - name: web
      port: {{ .Values.backend.service.ports.http }}
      protocol: TCP
      targetPort: web
