apiVersion: v2
name: dbildungs-iam-server
version: 0.2.0
description: dBildungs-IAM-server
type: application
appVersion: ""
dependencies:
- name: redis-cluster
  repository: https://charts.bitnami.com/bitnami
  version: 10.0.1
  condition: redis.redis-cluster.enabled