name: 'Nest Test & Sonarcloud'

on:
  workflow_call:

env:
  NODE_VERSION: '18'
  DEPLOY_STAGE: 'dev'

jobs:
  nest_lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Run linter
        run: npm run lint
  nest_test_cov:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker check
        run: docker --version
      - name: Inject Secrets
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'secrets.json'
          fileDir: './config/'
          encodedString: ewogICAgIkRCIjogewogICAgICAgICJTRUNSRVQiOiAiVmVyeSBoaWRkZW4gc2VjcmV0IgogICAgfSwKICAgICJLRVlDTE9BSyI6IHsKICAgICAgICAiUEFTU1dPUkQiOiAiQWRtaW5QYXNzd29yZCIKICAgIH0KfQ==
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Run tests
        run: npm run test:ci
      - name: Save test artifacts
        run: |
            mkdir -p coverage
            mv ./coverage artifacts
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: artifacts/
  code_analysis:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [nest_test_cov]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-artifacts
          path: artifacts/
      - name: SonarCloud upload
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}